//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.269
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRServer.Plugin.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IRServer.Plugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;DocumentElement&gt;
        ///  &lt;RemoteTable RawCode=&quot;31713&quot; AbstractButton=&quot;Up&quot; /&gt;
        ///  &lt;RemoteTable RawCode=&quot;31712&quot; AbstractButton=&quot;Down&quot; /&gt;
        ///  &lt;RemoteTable RawCode=&quot;31711&quot; AbstractButton=&quot;Left&quot; /&gt;
        ///  &lt;RemoteTable RawCode=&quot;31710&quot; AbstractButton=&quot;Right&quot; /&gt;
        ///  &lt;RemoteTable RawCode=&quot;31709&quot; AbstractButton=&quot;OK&quot; /&gt;
        ///  &lt;RemoteTable RawCode=&quot;31727&quot; AbstractButton=&quot;VolumeUp&quot; /&gt;
        ///  &lt;RemoteTable RawCode=&quot;31726&quot; AbstractButton=&quot;VolumeDown&quot; /&gt;
        ///  &lt;RemoteTable RawCode=&quot;31725&quot; AbstractButton=&quot; [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string AbstractMapping {
            get {
                return ResourceManager.GetString("AbstractMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;ehomelist version=&quot;1&quot;&gt;
        ///  &lt;transceiver deviceid=&quot;#vid_0471&amp;amp;pid_0815&quot; name=&quot;Microsoft/Philips 2005&quot; /&gt;
        ///  &lt;transceiver deviceid=&quot;#vid_045e&amp;amp;pid_006d&quot; name=&quot;Microsoft/Philips 2004&quot; /&gt;
        ///  &lt;transceiver deviceid=&quot;#vid_1460&amp;amp;pid_9150&quot; name=&quot;HP&quot; /&gt;
        ///  &lt;transceiver deviceid=&quot;#vid_107b&amp;amp;pid_3009&quot; name=&quot;FIC Spectra/Mycom Mediacenter&quot; /&gt;
        ///  &lt;transceiver deviceid=&quot;#vid_0609&amp;amp;pid_031d&quot; name=&quot;Toshiba/Hauppauge SMK MCE remote&quot; /&gt;
        ///  &lt;transceiver dev [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string eHomeTransceiverList {
            get {
                return ResourceManager.GetString("eHomeTransceiverList", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
